/**
 * THIS MODEL IS ONLY USED FOR FIREBASE (FIRESTORE DB)
 */



 class Employee {
   constructor(id, name, designation) {
     this.id = id; // represents the id generated by the firestore
     this.name = name;
     this.designation = designation;     
   }
 }
  
 module.exports = Employee;